version: "3.4"

services:
  openresty:
    build:
      context: openresty
    network_mode: host
    restart: always
    volumes:
      - configurations:/configurations
      - content:/content
      - certificates:/etc/resty-auto-ssl

volumes:
  configurations:
  content:
  certificates: