version: "3.4"

services:
  openresty:
    build:
      context: ./openresty
    image: openresty-letsencrypt-autoreload
    volumes:
      - ./mnt/configurations:/configurations
      - ./mnt/content:/content
      - ./mnt/certificates:/etc/resty-auto-ssl
    network_mode: "host"