version: "3.4"

services:
  openresty:
    build:
      context: ./openresty
    image: openresty-letsencrypt-autoreload
    deploy:
      mode: global
    volumes:
      - ./mnt/configurations:/configurations
      - ./mnt/content:/content
      - ./mnt/certificates:/etc/resty-auto-ssl
    ports:
      - 80:80
      - 443:443